### ISSUE TITLE
mooltiapp does not start minimized.

### ISSUE THREAD

**Issue by randomisresistance** [limpkin/mooltiapp#27]
Hi there,

I'm using Linux Mint as my main distribution. To start mooltiapp I have to add a entry in` "Startup Application"`. By doing so every time I login, X will start mooltiapp but not minimized. It would be nice to have a command line parameter like `--minimized` so that the app does not open the program main window.

I checked the code and found the corresponding line in:
[main.js](https://github.com/limpkin/mooltiapp/search?utf8=%E2%9C%93&q=minimize&type=)

But since I'm not so much a JavaScript coder I don't see what the problem is. But I guess it should not be hard to add this kind of option for users like me. 

Best regards,
RandomIsResistance

**Comment by limpkin** [comment]
Hello,

There's actually a command parameter for that. I'm in holidays but I'm
fairly sure it is --minimized or -minimized

Regards

**Comment by randomisresistance** [comment]
Hi limpkin,

ok, I tried both, but it does not work. 
I guess than it is a problem with the cinnamon desktop environment than. 

That is why I'm wondering I found the fix from [mediaslav](https://github.com/limpkin/mooltiapp/pull/22/commits/8fcc615eab8ecb17498f17975b1b2286c9f9093c) but it still seems to be a problem with my desktop environment. Same for Windows, but I guess this issue is already known.

Regards

**Comment by randomisresistance** [comment]
Me again,

I have to admit, I missed the last change ins main.js.

The correct parameter is `-m`
The coresponding change in the code is here: [f404738](https://github.com/limpkin/mooltiapp/commit/f40473868eeb9a323fda0204257176e5e33350d8#diff-3c56f1dfc265d93d754c52ea6397c36a)

Regards

**Comment by limpkin** [comment]
glad that worked!
