### ISSUE TITLE
Need to lock device

### ISSUE THREAD

**Issue by bredator** [limpkin/mooltiapp#29]
Is it possible to add an option that the device is sending Win+L to the device, when the card is removed? There isn't any need for the reverse way (you have to login like everywhere else), but it would be great, if the device will be locked after the card is removed.

**Comment by limpkin** [comment]
are you talking about the unlock/lock functionality described in the user manual?

**Comment by bredator** [comment]
I've tried it, but I don't understand, what it means. Also it seems, that nothing changes in the devices behaviour. I need a "Card removed"-Action, in my case "send Win+L when card removed is triggered".

**Comment by limpkin** [comment]
did you create a service named _unlock_ ?

**Comment by bredator** [comment]
Holy... after locking it once and unlock with _unlock_, it works with card removing. Great!! I think, we will buy more for our company ;) Thank you

**Comment by limpkin** [comment]
Hello,

Glad that did the trick :)
